name: Delete Old Workflow Runs

on:
  schedule:
    - cron: '0 0 0 * *'  
  workflow_dispatch:

jobs:
  delete-old-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List workflow runs
        id: list-runs
        run: |
          response=$(gh api -X GET /repos/${{ github.repository }}/actions/runs?per_page=100)
          echo "$response" > runs.json
          jq -r '.workflow_runs[] | select(.conclusion == "success") | .id' runs.json > run_ids.txt

      - name: Delete old workflow runs
        if: steps.list-runs.outputs.run_ids
        run: |
          run_ids=( $(cat run_ids.txt) )
          if [ ${#run_ids[@]} -gt 24 ]; then
            old_run_ids=( ${run_ids[@]:24} )
            for run_id in "${old_run_ids[@]}"; do
              gh api -X DELETE /repos/${{ github.repository }}/actions/runs/$run_id
            done
          fi
