name: 更新 Spider

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
      # Step 0: 删除之前的任务流
      - name: 删除之前的任务流
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          runs_to_delete=$(curl -s -H "Authorization: token $PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ github.ref_name }} \
            | jq -r '.workflow_runs | map(select(.status == "completed")) | .[10:] | .[].id')

          for run_id in $runs_to_delete; do
            echo "Deleting run $run_id"
            curl -X DELETE -H "Authorization: token $PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id
          done

      # Step 1: 查看 repository
      - name: 查看 repository
        uses: actions/checkout@v2

      # Step 2: 设置 Python 环境
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: 安装依赖项
      - name: 安装 Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: 获取 Spider URL 并设置环境变量
      - name: 获取 Spider 字段
        run: |
          SPIDER_URL=$(python -c "import requests; print(requests.get('https://9280.kstore.space/wex.json').json()['spider'])")
          echo "SPIDER_URL=$SPIDER_URL" >> $GITHUB_ENV

      # Step 5: 比较现有 Spider URL
      - name: 对比现有 Spider URL
        id: compare-urls
        env:
          SPIDER_JSON: ${{ secrets.SPIDER_JSON }}
        run: |
          EXISTING_SPIDER_URL=$(python -c "import requests; print(requests.get('${{ env.SPIDER_JSON }}').json()['spider'].strip())")
          SPIDER_URL=$(echo $SPIDER_URL | tr -d '\n' | tr -d ' ')
          EXISTING_SPIDER_URL=$(echo $EXISTING_SPIDER_URL | tr -d '\n' | tr -d ' ')
          
          if [ "$SPIDER_URL" = "$EXISTING_SPIDER_URL" ]; then
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "continue=true" >> $GITHUB_ENV

      # Step 6: 更新 Spider 字段并上传 Kstore
      - name: 更新 Spider 字段、并上传 Kstore
        if: env.continue == 'true'
        env:
          KSTORE_TOKEN: ${{ secrets.KSTORE_TOKEN }}
          KSTORE_TOKEN2: ${{ secrets.KSTORE_TOKEN2 }}
          KSTORE_ID: ${{ secrets.KSTORE_ID }}
          WEX_JSON: ${{ secrets.WEX_JSON }}
        run: |
          response=$(curl -s ${{ env.WEX_JSON }})
          updated_data=$(echo "$response" | python -c "import sys, json; data = json.load(sys.stdin); data['spider'] = '${SPIDER_URL}'; print(json.dumps(data, ensure_ascii=False))")
          echo "$updated_data" > spider.json
          curl -F "file=@spider.json" "https://upload.kstore.space/upload/${{ env.KSTORE_ID }}?access_token=${{ env.KSTORE_TOKEN2 }}"
          echo "$updated_data" > wex.json
          curl -F "file=@wex.json" "https://upload.kstore.space/upload/${{ env.KSTORE_ID }}?access_token=${{ env.KSTORE_TOKEN }}"

      # Step 7: 等待下一个预定时间（仅在 push 触发时）
      - name: 等待下一个预定时间
        if: startsWith(github.ref_name, 'refs/heads/main') && workflow.event_name != 'schedule'
        run: |
          current_time=$(date +%H:%M)
          next_run_time=$(date -d '1 hour' +%H:%M)
          wait_time=$(( (next_run_time - current_time) * 60 ))

          if [ "$current_time" == "$next_run_time" ]; then
            wait_time=60
          fi

          echo "当前时间: $current_time"
          echo "下一个预定运行时间: $next_run_time"
          echo "等待时间: $wait_time 分钟"

          sleep $wait_time
