name: 更新 Spider

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '11 20 * * *'

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 查看 repository
        uses: actions/checkout@v2

      # Step 2: Setup Python
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install necessary dependencies
      - name: 安装 Dependencies
        run: python -m pip install requests

      # Step 4: Get Spider URL and set environment variable
      - name: 获取 Spider 字段
        run: |
          SPIDER_URL=$(python -c "import requests; print(requests.get('https://9280.kstore.space/wex.json').json()['spider'])")
          echo "SPIDER_URL=$SPIDER_URL" >> $GITHUB_ENV

      # Step 4.5: Compare with existing Spider URL
      - name: 对比现有 Spider URL
        env:
          SPIDER_JSON: ${{ secrets.SPIDERR_JSON }}
        run: |
          EXISTING_SPIDER_URL=$(python -c "import requests; print(requests.get('${{ env.SPIDER_JSON }}').json()['spider'])")
          if [ "$SPIDER_URL" = "$EXISTING_SPIDER_URL" ]; then
            echo "Spider URL 是一样的。停止脚本."
            exit 0
          else
            echo "Spider URL 是不同的。继续脚本."
          fi

      # Step 5: Update Spider Field and upload to Kstore
      - name: 更新 Spider 字段、并上传 Kstore
        env:
          KSTORE_TOKEN: ${{ secrets.KSTORE_TOKEN }}
          KSTORE_TOKEN2: ${{ secrets.KSTORE_TOKEN2 }}
          KSTORE_ID: ${{ secrets.KSTORE_ID }}
          WEX_JSON: ${{ secrets.WEX_JSON }}
        run: |
          # Fetch existing data
          response=$(curl -s ${{ env.WEX_JSON }})
          
          # Update the 'spider' field with the new value
          updated_data=$(echo $response | python -c "import sys, json; data = json.load(sys.stdin); data['spider'] = '${{ env.SPIDER_URL }}'; print(json.dumps(data))")

          # Save updated data to spider.json
          cd ${{ github.workspace }}
          echo "$updated_data" > spider.json
          
          # Upload the updated spider.json to Kstore
          curl -F "file=@spider.json" "https://upload.kstore.space/upload/${{ env.KSTORE_ID }}?access_token=${{ env.KSTORE_TOKEN2 }}"

          # Save updated data to wex.json
          echo "$updated_data" > wex.json
          
          # Upload the updated wex.json to Kstore
          curl -F "file=@wex.json" "https://upload.kstore.space/upload/${{ env.KSTORE_ID }}?access_token=${{ env.KSTORE_TOKEN }}"
