name: 更新 wex

on:
  push:
    branches:
      - wex
  workflow_dispatch:
  schedule:
    - cron: '*/55 * * * *'  # 每55分钟执行一次

jobs:
  update-spider:
    runs-on: ubuntu-latest

    steps:
      # Step 0: Delete previous runs
      - name: 删除任务流
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          completed_runs=$(curl -s -H "Authorization: token $PAT" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ github.ref_name }}&status=completed" \
          | jq -r '.workflow_runs | .[72:] | .[].id')
      
          if [ -n "$completed_runs" ]; then
          echo "$completed_runs" | xargs -n 1 -I {} curl -s -X DELETE -H "Authorization: token $PAT" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/{}"
          fi

      # Step 1: Checkout the repository
      - name: 检出代码库
        uses: actions/checkout@v2

      # Step 2: Setup Python
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Cache dependencies
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Install necessary dependencies
      - name: 安装依赖
        run: python -m pip install requests

      # Step 5: Get and Edit JSON Content
      - name: 获取并编辑 JSON 内容
        id: edit-json
        env:
          WEX_JSON_URL: https://9280.kstore.space/wex.json
        run: |
          response=$(curl -s ${{ env.WEX_JSON_URL }})
          edited_data=$(echo "$response" | python -c "
          import sys, json;
          data = json.load(sys.stdin);
          data = [entry for entry in data if entry['key'] not in ['Doubana', 'Wexconfig']];
          for entry in data:
          if entry['name'] == '公众号：王二小放牛娃':
          entry['name'] = '推荐';
          print(json.dumps(data, ensure_ascii=False))")
          echo \"$edited_data\" > edited_wex.json

      # Step 6: Upload Edited JSON Content
      - name: 上传编辑后的 JSON 内容
        env:
          KSTORE_TOKEN: ${{ secrets.KSTORE_TOKEN }}
          KSTORE_ID: ${{ secrets.KSTORE_ID }}
        run: |
          curl -F \"file=@edited_wex.json\" \"https://upload.kstore.dev/upload/${{ env.KSTORE_ID }}?access_token=${{ env.KSTORE_TOKEN }}\"