name: Delete All Runs Manually

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  delete-all-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Delete all runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 进行认证
        run: |
          import os
          import requests

          # GitHub API URL to list workflow runs
          repo = os.getenv('GITHUB_REPOSITORY')
          url = f'https://api.github.com/repos/{repo}/actions/runs'

          headers = {
              'Authorization': f'token {os.getenv("GITHUB_TOKEN")}',
              'Accept': 'application/vnd.github.v3+json'
          }

          # Fetch the list of all runs
          response = requests.get(url, headers=headers)
          runs = response.json().get('workflow_runs', [])

          # Delete all runs
          for run in runs:
              run_id = run['id']
              delete_url = f'https://api.github.com/repos/{repo}/actions/runs/{run_id}'
              delete_response = requests.delete(delete_url, headers=headers)
              if delete_response.status_code == 204:
                  print(f'Deleted run {run_id}')
              else:
                  print(f'Failed to delete run {run_id}: {delete_response.status_code}')

          print('All runs deleted successfully.')