name: Run Runs Branch Workflow

# 触发器配置
on:
  workflow_dispatch:  # 允许手动触发

jobs:
  run-runs-workflow:
    runs-on: ubuntu-latest

    steps:
      # 切换到 runs 分支
      - name: Checkout runs branch
        uses: actions/checkout@v3
        with:
          ref: runs  # 指定 runs 分支

      # 运行 runs 分支中的 YAML 脚本
      - name: Run runs branch workflow
        env:
          PAT: ${{ secrets.PAT }}  # 使用 GitHub Secrets 中的 PAT
          RUN_ID: ${{ github.event.inputs.run_id }}  # 从手动触发输入中获取 run_id
        run: |
          curl -X DELETE \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $PAT" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID